@baseUrl = http://localhost:3000
@contactPrefix = /api/contacts

POST {{baseUrl}}/api/users/register
Content-Type: application/json
Accept: application/json

{
  "username" : "rizky",
  "name" : "cahyono",
  "password" : "rahasia12345"
}

### Login

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "rizky",
  "password" : "rahasia12345"
}


### search all
GET {{baseUrl}}{{contactPrefix}}
Authorization: f3ea519b-ae94-4e7a-a6af-e142000b94ba

### search by name
GET {{baseUrl}}{{contactPrefix}}?name=es
Authorization: f3ea519b-ae94-4e7a-a6af-e142000b94ba

